# Generated by Django 3.2.5 on 2022-04-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tcin', models.FloatField()),
                ('Tcout', models.FloatField()),
                ('Thin', models.FloatField()),
                ('Thout', models.FloatField()),
                ('Fcold', models.FloatField()),
                ('Fhot', models.FloatField()),
                ('Tsetpt', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HX_setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tcin_id', models.TextField(max_length=15)),
                ('Tcout_id', models.TextField(max_length=15)),
                ('Thin_id', models.TextField(max_length=15)),
                ('Thout_id', models.TextField(max_length=15)),
            ],
        ),
    ]
