# Generated by Django 3.2.5 on 2022-04-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HX', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hx_setup',
            name='Tsetpt_id',
            field=models.TextField(default=123456789012345, max_length=15),
            preserve_default=False,
        ),
    ]
