# Generated by Django 3.2.5 on 2022-04-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HX', '0002_hx_setup_tsetpt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hx',
            name='Fcold',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='hx',
            name='Fhot',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='hx',
            name='Tcin',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='hx',
            name='Tcout',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='hx',
            name='Thin',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='hx',
            name='Thout',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='hx',
            name='Tsetpt',
            field=models.FloatField(default=0.0),
        ),
    ]
