# Generated by Django 3.2.5 on 2022-04-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HX', '0004_auto_20220409_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hx',
            name='Tsetpt_live',
        ),
    ]
