# Generated by Django 3.2.5 on 2022-04-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HX', '0005_remove_hx_tsetpt_live'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hx',
            old_name='Fcold',
            new_name='Tcold',
        ),
        migrations.RenameField(
            model_name='hx',
            old_name='Fhot',
            new_name='Thot',
        ),
        migrations.RemoveField(
            model_name='hx',
            name='Tsetpt',
        ),
    ]
